// AM COLLECTION - Master Copy Luxury Watch Products Data
const PRODUCTS_DATA = [
  {
    id: 'amc-01',
    brand: 'Rolex',
    model: 'Submariner Date 41mm Ceramic',
    tagline: '1:1 Super Clone Master Edition',
    price: 4499,
    originalPrice: 1150000,
    rating: 4.9,
    reviewsCount: 148,
    badge: 'BEST SELLER',
    category: 'rolex',
    movement: 'Japanese Automatic Movement',
    dialSize: '41 mm',
    glass: 'Sapphire Crystal (Anti-Reflective)',
    strap: 'Solid 904L Stainless Steel Oyster',
    waterResistance: 'Daily Splash & Rain Proof (30m)',
    clasp: 'Oysterlock safety clasp with Glidelock',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    description: 'The archetype of the diver’s watch. Featuring exact 1:1 weight, unidirectional rotating ceramic bezel with platinum coated graduations, and sweeping second hand.',
    features: [
      'Exact 1:1 weight & dimensions',
      'Ceramic rotating Cerachrom bezel',
      'Sweeping smooth automatic movement',
      'Luminescent Chromalight hands & indices',
      'Laser etched crown at 6 o’clock on glass'
    ]
  },
  {
    id: 'amc-02',
    brand: 'Rolex',
    model: 'Cosmograph Daytona Yellow Gold',
    tagline: 'Oysterflex Chronograph Master Edition',
    price: 5999,
    originalPrice: 2850000,
    rating: 5.0,
    reviewsCount: 204,
    badge: 'PREMIUM MASTER',
    category: 'rolex',
    movement: 'Functional Chronograph Automatic',
    dialSize: '40 mm',
    glass: 'Scratch-Proof Sapphire Glass',
    strap: 'High-Density Oysterflex Black Rubber',
    waterResistance: 'Daily Splash Proof',
    clasp: '18K Yellow Gold Plated Folding Oysterlock',
    image: 'https://images.unsplash.com/photo-1547996160-71dfabb1a7b1?q=80&w=800&auto=format&fit=crop',
    description: 'Designed to meet the demands of racing drivers. Iconic black Cerachrom bezel with tachymetric scale in 18 ct yellow gold electroplating.',
    features: [
      'Working chronograph sub-dials',
      'Deep 18k thick gold electroplating',
      'Heavy premium weight matching original',
      'Oysterflex elastomer strap with inner metal blade',
      'Engraved tachymeter scale on bezel'
    ]
  },
  {
    id: 'amc-03',
    brand: 'Patek Philippe',
    model: 'Nautilus 5711/1R Rose Gold',
    tagline: 'Iconic Horology Master Clone',
    price: 6499,
    originalPrice: 6500000,
    rating: 4.9,
    reviewsCount: 182,
    badge: 'ULTRA LUXURY',
    category: 'patek',
    movement: 'Miyota Japanese Automatic Movement',
    dialSize: '40 mm',
    glass: 'Double AR-Coated Sapphire Crystal',
    strap: 'Rose Gold Plated Brushed & Polished Steel',
    waterResistance: '30m Water Resistant',
    clasp: 'Nautilus fold-over clasp',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop',
    description: 'The pinnacle of luxury sports watches. Featuring the rounded octagonal bezel, ingenious porthole construction of its case and horizontally embossed dial.',
    features: [
      'Exquisite horizontal embossed dial texture',
      'Exhibition see-through sapphire case back',
      'Brushed and mirror-polished case finishing',
      'Smooth gliding rose gold bracelet',
      'Date display at 3 o’clock'
    ]
  },
  {
    id: 'amc-04',
    brand: 'Audemars Piguet',
    model: 'Royal Oak Double Balance Wheel',
    tagline: 'Openworked Skeleton Masterpiece',
    price: 6999,
    originalPrice: 7500000,
    rating: 5.0,
    reviewsCount: 96,
    badge: 'SKELETON MASTER',
    category: 'ap',
    movement: 'Skeleton Automatic Movement',
    dialSize: '41 mm',
    glass: 'Curved Scratch-Resistant Sapphire',
    strap: 'Integrated Stainless Steel Royal Oak Bracelet',
    waterResistance: 'Splash Proof',
    clasp: 'AP folding clasp with twin safety pushers',
    image: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?q=80&w=800&auto=format&fit=crop',
    description: 'A feast for the eyes. Full skeletonized dial showing the intricate movement gears, famous octagonal bezel with 8 hexagonal white gold screws.',
    features: [
      'Visible skeleton mechanics front and back',
      'Signature octagonal bezel with polished screws',
      'Tapered integrated AP stainless steel bracelet',
      'Dual balance wheel visual simulation',
      'Heavy solid wrist feel (170g+)'
    ]
  },
  {
    id: 'amc-05',
    brand: 'Audemars Piguet',
    model: 'Royal Oak Chronograph 41mm Blue',
    tagline: 'Grande Tapisserie Royal Oak',
    price: 5899,
    originalPrice: 3800000,
    rating: 4.8,
    reviewsCount: 134,
    badge: 'TOP RATED',
    category: 'ap',
    movement: 'High-Precision Chronograph Movement',
    dialSize: '41 mm',
    glass: 'Glareproof Sapphire Crystal',
    strap: 'Hand-finished Brushed Stainless Steel',
    waterResistance: '30m Daily Water Resistant',
    clasp: 'AP Double-Deployant Buckle',
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=800&auto=format&fit=crop',
    description: 'Blue dial with “Grande Tapisserie” pattern, rhodium-toned counters, luminescent Royal Oak hands and white gold applied hour-markers.',
    features: [
      'Genuine 3D “Grande Tapisserie” guilloche pattern',
      'Active stopwatch chronograph subdials',
      'Iconic Gérald Genta design proportions',
      'Double push-button deployment buckle',
      'Sharp beveled edge hand finishing'
    ]
  },
  {
    id: 'amc-06',
    brand: 'Casio Vintage',
    model: 'Vintage Digital Gold A168WG-9WDF',
    tagline: 'Retro Classic All-Gold Edition',
    price: 1899,
    originalPrice: 4495,
    rating: 4.9,
    reviewsCount: 320,
    badge: 'HOT DEAL',
    category: 'casio',
    movement: 'Japanese Digital Quartz Caliber',
    dialSize: '36.3 mm',
    glass: 'Hardened Mineral Resin Glass',
    strap: 'Adjustable Stainless Steel Gold Mesh Band',
    waterResistance: 'Water Resistant for Daily Use',
    clasp: 'Sliding micro-adjustable clasp',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop',
    description: 'The golden icon of 80s timeless style. Featuring classic gold ion plating, electroluminescent backlight, 1/100-second stopwatch, daily alarm and auto calendar.',
    features: [
      'Original ElectroLuminescent blue-green backlight',
      '1/100-second precision stopwatch & timer',
      'Daily alarm & hourly time signal',
      'Self-adjustable clasp (no tool required)',
      'Featherlight & extremely comfortable on wrist'
    ]
  },
  {
    id: 'amc-07',
    brand: 'Rolex',
    model: 'Datejust 41 Fluted Slate Roman (Wimbledon)',
    tagline: 'Jubilee Two-Tone Everose Gold',
    price: 4699,
    originalPrice: 1450000,
    rating: 4.9,
    reviewsCount: 165,
    badge: 'CELEBRITY CHOICE',
    category: 'rolex',
    movement: 'Japanese Automatic Self-Winding',
    dialSize: '41 mm',
    glass: 'Sapphire with 2.5x Cyclops Date Magnifier',
    strap: 'Five-Piece Jubilee Two-Tone Bracelet',
    waterResistance: 'Splash Proof',
    clasp: 'Folding Oysterclasp with Easylink 5mm',
    image: 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?q=80&w=800&auto=format&fit=crop',
    description: 'The world-renowned Wimbledon edition. Slate grey sunray dial adorned with dark green Roman numerals outlined in black, paired with radiant fluted bezel.',
    features: [
      'Accurate green outlined Roman numerals',
      'Fluted bezel capturing light at every angle',
      'Supple 5-link Jubilee bracelet with smooth links',
      'Magnified date aperture at 3 o’clock',
      'Sweeping second hand without tick-tock stutter'
    ]
  },
  {
    id: 'amc-08',
    brand: 'Patek Philippe',
    model: 'Aquanaut 5167A Black Dial',
    tagline: 'Modern Sport Chic Master Clone',
    price: 5499,
    originalPrice: 4200000,
    rating: 4.8,
    reviewsCount: 119,
    badge: 'LIMITED STOCK',
    category: 'patek',
    movement: 'Japanese Automatic Movement',
    dialSize: '40.8 mm',
    glass: 'Sapphire Crystal with Anti-Glare Coating',
    strap: 'Ultra-Resistant Tropical Black Rubber',
    waterResistance: 'Daily Waterproof',
    clasp: 'Fold-over Aquanaut clasp',
    image: 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=800&auto=format&fit=crop',
    description: 'Youthful, dynamic and casually elegant. The embossed dial reflects the textured pattern of the waterproof strap made of high-tech composite material.',
    features: [
      'Curved octagonal case silhouette',
      'Geosphere embossed dial texture',
      'Premium dust-repellent tropical rubber strap',
      'Luminescent Arabic numerals and hands',
      'Transparent back with engraved rotor'
    ]
  },
  {
    id: 'amc-09',
    brand: 'Cartier',
    model: 'Santos de Cartier Large Two-Tone',
    tagline: 'Aviation Heritage Square Icon',
    price: 4999,
    originalPrice: 1050000,
    rating: 4.9,
    reviewsCount: 142,
    badge: 'ROYAL HERITAGE',
    category: 'cartier',
    movement: 'Japanese Automatic Movement',
    dialSize: '39.8 mm',
    glass: 'High-Purity Sapphire Crystal',
    strap: 'Two-Tone Gold & Steel with SmartLink Screws',
    waterResistance: 'Daily Splash Proof',
    clasp: 'Double deployant hidden butterfly buckle',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop',
    description: 'The first purpose-designed modern wristwatch. Famous square bezel fastened with eight visible screws and graduated Roman dial with sword-shaped blued hands.',
    features: [
      'Signature 7-sided crown set with blue synthetic spinel',
      'Sword-shaped blued steel hands',
      'Satin-brushed case with mirror-polished beveled edges',
      'Iconic Cartier secret signature at VII hour marker',
      'Comfortable wrist curvature for ergonomic fit'
    ]
  },
  {
    id: 'amc-10',
    brand: 'Hublot',
    model: 'Big Bang Unico King Gold Ceramic',
    tagline: 'The Art of Fusion Master Clone',
    price: 5299,
    originalPrice: 2400000,
    rating: 4.7,
    reviewsCount: 88,
    badge: 'BOLD & ICONIC',
    category: 'hublot',
    movement: 'Quartz Flyback Chronograph System',
    dialSize: '44 mm',
    glass: 'Sapphire Crystal with Anti-Reflective Treatment',
    strap: 'Structured Lined Black Rubber Strap',
    waterResistance: 'Daily Splash Proof',
    clasp: '18K King Gold Plated Deployant Buckle',
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=800&auto=format&fit=crop',
    description: 'A revolutionary timepiece blending high-tech ceramic with King Gold hue. Features openwork matte black dial with red accents and column-wheel mechanism.',
    features: [
      'Bold 44mm statement case construction',
      'Satin-finished and polished black ceramic bezel',
      'H-shaped titanium bezel screws',
      'Ribbed high-grade vulcanized rubber strap',
      'Quick-release “One Click” strap system look'
    ]
  },
  {
    id: 'amc-11',
    brand: 'Omega',
    model: 'Speedmaster Professional Moonwatch',
    tagline: 'The First Watch Worn on the Moon',
    price: 4799,
    originalPrice: 780000,
    rating: 5.0,
    reviewsCount: 175,
    badge: 'LEGENDARY MOON',
    category: 'omega',
    movement: 'Mechanical Chronograph Movement',
    dialSize: '42 mm',
    glass: 'Sapphire Crystal (Front & Exhibition Back)',
    strap: 'Brushed Five-Arched-Links Stainless Steel',
    waterResistance: '30m Splash Proof',
    clasp: 'Foldover clasp with comfort setting',
    image: 'https://images.unsplash.com/photo-1594576722512-582bcd46fba3?q=80&w=800&auto=format&fit=crop',
    description: 'Part of all six moon landings. Asymmetrical case, step dial, the famous dot over 90 on the anodised aluminium bezel ring and legendary chronograph subdials.',
    features: [
      'Historic “Dot Over 90” tachymeter bezel ring',
      'Step dial with recessed sub-dials',
      'Super-LumiNova hour indices',
      'Smooth chronograph pusher actuation',
      'Engraved Seahorse medallion and sapphire caseback'
    ]
  },
  {
    id: 'amc-12',
    brand: 'Casio Vintage',
    model: 'Edifice Chronograph EFR Rose-Gold Edition',
    tagline: 'Speed & Intelligence Executive Series',
    price: 2499,
    originalPrice: 11995,
    rating: 4.8,
    reviewsCount: 210,
    badge: 'VALUE MASTER',
    category: 'casio',
    movement: 'Japanese Multi-Dial Quartz Chrono',
    dialSize: '43 mm',
    glass: 'Mineral Glass with Anti-Scratch Coating',
    strap: 'Genuine Perforated Leather Band',
    waterResistance: '50m Water Resistant',
    clasp: 'Rose Gold Plated Tang Buckle',
    image: 'https://images.unsplash.com/photo-1526045478516-99145907023c?q=80&w=800&auto=format&fit=crop',
    description: 'Motorsport inspired dynamic chronograph with rose gold ion plated case, multi-layered black carbon fiber dial texture, and genuine leather racing strap.',
    features: [
      'Triple sub-dial chronograph with date window',
      'Rose gold ionic plating with high luster',
      'Genuine padded leather strap with contrast stitch',
      'Long-lasting Japanese battery lifespan (3+ years)',
      'Substantial masculine wrist presence'
    ]
  }
];

// Fallback image helper
function getWatchImage(url) {
  return url || 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop';
}
